spring.datasource.url=???
spring.datasource.username=???
spring.datasource.password=???
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=8080
logging.level.org.springframeworkweb=DEBUG
logging.level.org.springframework.security=DEBUG
server.servlet.session.timeout=86400
server.servlet.session.cookie.max-age=86400

